name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install prerequisites
      run: sudo apt update && sudo apt install curl cabextract libusb-1.0-0-dev
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make (debug)
      run: make clean && make BUILD=DEBUG
    - name: Make (release)
      run: make clean && make BUILD=RELEASE
